# Docker profile
spring.datasource.url=jdbc:mariadb://database:3306/booking
spring.datasource.username=booking
spring.datasource.password=booking

spring.liquibase.contexts=docker

spring.mail.host=mailpit
spring.mail.port=1025
