/**
 * Country data for phone prefixes and flag icons
 * Used in phone country code select and language switcher
 */

export interface Country {
  iso2: string; // ISO 3166-1 alpha-2 code
  name: string; // Country name
  phonePrefix: string; // Phone prefix (e.g., "+49")
  flagPath: string; // Path to SVG file
}

/**
 * Complete list of countries with phone prefixes and flag paths
 * Flags are stored in public/assets/flags/ and served statically
 */
export const COUNTRIES: Country[] = [
  { iso2: 'AF', name: 'Afghanistan', phonePrefix: '+93', flagPath: '/assets/flags/af.svg' },
  { iso2: 'AL', name: 'Albania', phonePrefix: '+355', flagPath: '/assets/flags/al.svg' },
  { iso2: 'DZ', name: 'Algeria', phonePrefix: '+213', flagPath: '/assets/flags/dz.svg' },
  { iso2: 'AD', name: 'Andorra', phonePrefix: '+376', flagPath: '/assets/flags/ad.svg' },
  { iso2: 'AO', name: 'Angola', phonePrefix: '+244', flagPath: '/assets/flags/ao.svg' },
  { iso2: 'AG', name: 'Antigua and Barbuda', phonePrefix: '+1-268', flagPath: '/assets/flags/ag.svg' },
  { iso2: 'AR', name: 'Argentina', phonePrefix: '+54', flagPath: '/assets/flags/ar.svg' },
  { iso2: 'AM', name: 'Armenia', phonePrefix: '+374', flagPath: '/assets/flags/am.svg' },
  { iso2: 'AU', name: 'Australia', phonePrefix: '+61', flagPath: '/assets/flags/au.svg' },
  { iso2: 'AT', name: 'Austria', phonePrefix: '+43', flagPath: '/assets/flags/at.svg' },
  { iso2: 'AZ', name: 'Azerbaijan', phonePrefix: '+994', flagPath: '/assets/flags/az.svg' },
  { iso2: 'BS', name: 'Bahamas', phonePrefix: '+1-242', flagPath: '/assets/flags/bs.svg' },
  { iso2: 'BH', name: 'Bahrain', phonePrefix: '+973', flagPath: '/assets/flags/bh.svg' },
  { iso2: 'BB', name: 'Barbados', phonePrefix: '+1-246', flagPath: '/assets/flags/bb.svg' },
  { iso2: 'BD', name: 'Bangladesh', phonePrefix: '+880', flagPath: '/assets/flags/bd.svg' },
  { iso2: 'BY', name: 'Belarus', phonePrefix: '+375', flagPath: '/assets/flags/by.svg' },
  { iso2: 'BE', name: 'Belgium', phonePrefix: '+32', flagPath: '/assets/flags/be.svg' },
  { iso2: 'BZ', name: 'Belize', phonePrefix: '+501', flagPath: '/assets/flags/bz.svg' },
  { iso2: 'BJ', name: 'Benin', phonePrefix: '+229', flagPath: '/assets/flags/bj.svg' },
  { iso2: 'BT', name: 'Bhutan', phonePrefix: '+975', flagPath: '/assets/flags/bt.svg' },
  { iso2: 'BO', name: 'Bolivia', phonePrefix: '+591', flagPath: '/assets/flags/bo.svg' },
  { iso2: 'BA', name: 'Bosnia and Herzegovina', phonePrefix: '+387', flagPath: '/assets/flags/ba.svg' },
  { iso2: 'BW', name: 'Botswana', phonePrefix: '+267', flagPath: '/assets/flags/bw.svg' },
  { iso2: 'BR', name: 'Brazil', phonePrefix: '+55', flagPath: '/assets/flags/br.svg' },
  { iso2: 'BN', name: 'Brunei', phonePrefix: '+673', flagPath: '/assets/flags/bn.svg' },
  { iso2: 'BG', name: 'Bulgaria', phonePrefix: '+359', flagPath: '/assets/flags/bg.svg' },
  { iso2: 'BF', name: 'Burkina Faso', phonePrefix: '+226', flagPath: '/assets/flags/bf.svg' },
  { iso2: 'BI', name: 'Burundi', phonePrefix: '+257', flagPath: '/assets/flags/bi.svg' },
  { iso2: 'KH', name: 'Cambodia', phonePrefix: '+855', flagPath: '/assets/flags/kh.svg' },
  { iso2: 'CM', name: 'Cameroon', phonePrefix: '+237', flagPath: '/assets/flags/cm.svg' },
  { iso2: 'CA', name: 'Canada', phonePrefix: '+1', flagPath: '/assets/flags/ca.svg' },
  { iso2: 'CV', name: 'Cape Verde', phonePrefix: '+238', flagPath: '/assets/flags/cv.svg' },
  { iso2: 'CF', name: 'Central African Republic', phonePrefix: '+236', flagPath: '/assets/flags/cf.svg' },
  { iso2: 'TD', name: 'Chad', phonePrefix: '+235', flagPath: '/assets/flags/td.svg' },
  { iso2: 'CL', name: 'Chile', phonePrefix: '+56', flagPath: '/assets/flags/cl.svg' },
  { iso2: 'CN', name: 'China', phonePrefix: '+86', flagPath: '/assets/flags/cn.svg' },
  { iso2: 'CO', name: 'Colombia', phonePrefix: '+57', flagPath: '/assets/flags/co.svg' },
  { iso2: 'KM', name: 'Comoros', phonePrefix: '+269', flagPath: '/assets/flags/km.svg' },
  { iso2: 'CG', name: 'Congo', phonePrefix: '+242', flagPath: '/assets/flags/cg.svg' },
  { iso2: 'CR', name: 'Costa Rica', phonePrefix: '+506', flagPath: '/assets/flags/cr.svg' },
  { iso2: 'CI', name: "Côte d'Ivoire", phonePrefix: '+225', flagPath: '/assets/flags/ci.svg' },
  { iso2: 'HR', name: 'Croatia', phonePrefix: '+385', flagPath: '/assets/flags/hr.svg' },
  { iso2: 'CU', name: 'Cuba', phonePrefix: '+53', flagPath: '/assets/flags/cu.svg' },
  { iso2: 'CY', name: 'Cyprus', phonePrefix: '+357', flagPath: '/assets/flags/cy.svg' },
  { iso2: 'CZ', name: 'Czech Republic', phonePrefix: '+420', flagPath: '/assets/flags/cz.svg' },
  { iso2: 'CD', name: 'Congo, Democratic Republic', phonePrefix: '+243', flagPath: '/assets/flags/cd.svg' },
  { iso2: 'DK', name: 'Denmark', phonePrefix: '+45', flagPath: '/assets/flags/dk.svg' },
  { iso2: 'DJ', name: 'Djibouti', phonePrefix: '+253', flagPath: '/assets/flags/dj.svg' },
  { iso2: 'DM', name: 'Dominica', phonePrefix: '+1-767', flagPath: '/assets/flags/dm.svg' },
  { iso2: 'DO', name: 'Dominican Republic', phonePrefix: '+1-809', flagPath: '/assets/flags/do.svg' },
  { iso2: 'EC', name: 'Ecuador', phonePrefix: '+593', flagPath: '/assets/flags/ec.svg' },
  { iso2: 'EG', name: 'Egypt', phonePrefix: '+20', flagPath: '/assets/flags/eg.svg' },
  { iso2: 'SV', name: 'El Salvador', phonePrefix: '+503', flagPath: '/assets/flags/sv.svg' },
  { iso2: 'GQ', name: 'Equatorial Guinea', phonePrefix: '+240', flagPath: '/assets/flags/gq.svg' },
  { iso2: 'ER', name: 'Eritrea', phonePrefix: '+291', flagPath: '/assets/flags/er.svg' },
  { iso2: 'EE', name: 'Estonia', phonePrefix: '+372', flagPath: '/assets/flags/ee.svg' },
  { iso2: 'ET', name: 'Ethiopia', phonePrefix: '+251', flagPath: '/assets/flags/et.svg' },
  { iso2: 'FJ', name: 'Fiji', phonePrefix: '+679', flagPath: '/assets/flags/fj.svg' },
  { iso2: 'FI', name: 'Finland', phonePrefix: '+358', flagPath: '/assets/flags/fi.svg' },
  { iso2: 'FR', name: 'France', phonePrefix: '+33', flagPath: '/assets/flags/fr.svg' },
  { iso2: 'GA', name: 'Gabon', phonePrefix: '+241', flagPath: '/assets/flags/ga.svg' },
  { iso2: 'GM', name: 'Gambia', phonePrefix: '+220', flagPath: '/assets/flags/gm.svg' },
  { iso2: 'GE', name: 'Georgia', phonePrefix: '+995', flagPath: '/assets/flags/ge.svg' },
  { iso2: 'DE', name: 'Germany', phonePrefix: '+49', flagPath: '/assets/flags/de.svg' },
  { iso2: 'GH', name: 'Ghana', phonePrefix: '+233', flagPath: '/assets/flags/gh.svg' },
  { iso2: 'GR', name: 'Greece', phonePrefix: '+30', flagPath: '/assets/flags/gr.svg' },
  { iso2: 'GD', name: 'Grenada', phonePrefix: '+1-473', flagPath: '/assets/flags/gd.svg' },
  { iso2: 'GT', name: 'Guatemala', phonePrefix: '+502', flagPath: '/assets/flags/gt.svg' },
  { iso2: 'GN', name: 'Guinea', phonePrefix: '+224', flagPath: '/assets/flags/gn.svg' },
  { iso2: 'GW', name: 'Guinea-Bissau', phonePrefix: '+245', flagPath: '/assets/flags/gw.svg' },
  { iso2: 'GY', name: 'Guyana', phonePrefix: '+592', flagPath: '/assets/flags/gy.svg' },
  { iso2: 'HT', name: 'Haiti', phonePrefix: '+509', flagPath: '/assets/flags/ht.svg' },
  { iso2: 'HN', name: 'Honduras', phonePrefix: '+504', flagPath: '/assets/flags/hn.svg' },
  { iso2: 'HK', name: 'Hong Kong', phonePrefix: '+852', flagPath: '/assets/flags/hk.svg' },
  { iso2: 'HU', name: 'Hungary', phonePrefix: '+36', flagPath: '/assets/flags/hu.svg' },
  { iso2: 'IS', name: 'Iceland', phonePrefix: '+354', flagPath: '/assets/flags/is.svg' },
  { iso2: 'IN', name: 'India', phonePrefix: '+91', flagPath: '/assets/flags/in.svg' },
  { iso2: 'ID', name: 'Indonesia', phonePrefix: '+62', flagPath: '/assets/flags/id.svg' },
  { iso2: 'IR', name: 'Iran', phonePrefix: '+98', flagPath: '/assets/flags/ir.svg' },
  { iso2: 'IQ', name: 'Iraq', phonePrefix: '+964', flagPath: '/assets/flags/iq.svg' },
  { iso2: 'IE', name: 'Ireland', phonePrefix: '+353', flagPath: '/assets/flags/ie.svg' },
  { iso2: 'IL', name: 'Israel', phonePrefix: '+972', flagPath: '/assets/flags/il.svg' },
  { iso2: 'IT', name: 'Italy', phonePrefix: '+39', flagPath: '/assets/flags/it.svg' },
  { iso2: 'JM', name: 'Jamaica', phonePrefix: '+1-876', flagPath: '/assets/flags/jm.svg' },
  { iso2: 'JP', name: 'Japan', phonePrefix: '+81', flagPath: '/assets/flags/jp.svg' },
  { iso2: 'JO', name: 'Jordan', phonePrefix: '+962', flagPath: '/assets/flags/jo.svg' },
  { iso2: 'KZ', name: 'Kazakhstan', phonePrefix: '+7', flagPath: '/assets/flags/kz.svg' },
  { iso2: 'KE', name: 'Kenya', phonePrefix: '+254', flagPath: '/assets/flags/ke.svg' },
  { iso2: 'KI', name: 'Kiribati', phonePrefix: '+686', flagPath: '/assets/flags/ki.svg' },
  { iso2: 'KW', name: 'Kuwait', phonePrefix: '+965', flagPath: '/assets/flags/kw.svg' },
  { iso2: 'KG', name: 'Kyrgyzstan', phonePrefix: '+996', flagPath: '/assets/flags/kg.svg' },
  { iso2: 'LA', name: 'Laos', phonePrefix: '+856', flagPath: '/assets/flags/la.svg' },
  { iso2: 'LV', name: 'Latvia', phonePrefix: '+371', flagPath: '/assets/flags/lv.svg' },
  { iso2: 'LB', name: 'Lebanon', phonePrefix: '+961', flagPath: '/assets/flags/lb.svg' },
  { iso2: 'LS', name: 'Lesotho', phonePrefix: '+266', flagPath: '/assets/flags/ls.svg' },
  { iso2: 'LR', name: 'Liberia', phonePrefix: '+231', flagPath: '/assets/flags/lr.svg' },
  { iso2: 'LY', name: 'Libya', phonePrefix: '+218', flagPath: '/assets/flags/ly.svg' },
  { iso2: 'LI', name: 'Liechtenstein', phonePrefix: '+423', flagPath: '/assets/flags/li.svg' },
  { iso2: 'LT', name: 'Lithuania', phonePrefix: '+370', flagPath: '/assets/flags/lt.svg' },
  { iso2: 'LU', name: 'Luxembourg', phonePrefix: '+352', flagPath: '/assets/flags/lu.svg' },
  { iso2: 'MO', name: 'Macao', phonePrefix: '+853', flagPath: '/assets/flags/mo.svg' },
  { iso2: 'MK', name: 'Macedonia', phonePrefix: '+389', flagPath: '/assets/flags/mk.svg' },
  { iso2: 'MG', name: 'Madagascar', phonePrefix: '+261', flagPath: '/assets/flags/mg.svg' },
  { iso2: 'MW', name: 'Malawi', phonePrefix: '+265', flagPath: '/assets/flags/mw.svg' },
  { iso2: 'MY', name: 'Malaysia', phonePrefix: '+60', flagPath: '/assets/flags/my.svg' },
  { iso2: 'MV', name: 'Maldives', phonePrefix: '+960', flagPath: '/assets/flags/mv.svg' },
  { iso2: 'ML', name: 'Mali', phonePrefix: '+223', flagPath: '/assets/flags/ml.svg' },
  { iso2: 'MT', name: 'Malta', phonePrefix: '+356', flagPath: '/assets/flags/mt.svg' },
  { iso2: 'MH', name: 'Marshall Islands', phonePrefix: '+692', flagPath: '/assets/flags/mh.svg' },
  { iso2: 'MR', name: 'Mauritania', phonePrefix: '+222', flagPath: '/assets/flags/mr.svg' },
  { iso2: 'MU', name: 'Mauritius', phonePrefix: '+230', flagPath: '/assets/flags/mu.svg' },
  { iso2: 'MX', name: 'Mexico', phonePrefix: '+52', flagPath: '/assets/flags/mx.svg' },
  { iso2: 'FM', name: 'Micronesia', phonePrefix: '+691', flagPath: '/assets/flags/fm.svg' },
  { iso2: 'MD', name: 'Moldova', phonePrefix: '+373', flagPath: '/assets/flags/md.svg' },
  { iso2: 'MC', name: 'Monaco', phonePrefix: '+377', flagPath: '/assets/flags/mc.svg' },
  { iso2: 'MN', name: 'Mongolia', phonePrefix: '+976', flagPath: '/assets/flags/mn.svg' },
  { iso2: 'ME', name: 'Montenegro', phonePrefix: '+382', flagPath: '/assets/flags/me.svg' },
  { iso2: 'MA', name: 'Morocco', phonePrefix: '+212', flagPath: '/assets/flags/ma.svg' },
  { iso2: 'MZ', name: 'Mozambique', phonePrefix: '+258', flagPath: '/assets/flags/mz.svg' },
  { iso2: 'MM', name: 'Myanmar', phonePrefix: '+95', flagPath: '/assets/flags/mm.svg' },
  { iso2: 'NA', name: 'Namibia', phonePrefix: '+264', flagPath: '/assets/flags/na.svg' },
  { iso2: 'NR', name: 'Nauru', phonePrefix: '+674', flagPath: '/assets/flags/nr.svg' },
  { iso2: 'NP', name: 'Nepal', phonePrefix: '+977', flagPath: '/assets/flags/np.svg' },
  { iso2: 'NL', name: 'Netherlands', phonePrefix: '+31', flagPath: '/assets/flags/nl.svg' },
  { iso2: 'NZ', name: 'New Zealand', phonePrefix: '+64', flagPath: '/assets/flags/nz.svg' },
  { iso2: 'NI', name: 'Nicaragua', phonePrefix: '+505', flagPath: '/assets/flags/ni.svg' },
  { iso2: 'NE', name: 'Niger', phonePrefix: '+227', flagPath: '/assets/flags/ne.svg' },
  { iso2: 'NG', name: 'Nigeria', phonePrefix: '+234', flagPath: '/assets/flags/ng.svg' },
  { iso2: 'KP', name: 'North Korea', phonePrefix: '+850', flagPath: '/assets/flags/kp.svg' },
  { iso2: 'NO', name: 'Norway', phonePrefix: '+47', flagPath: '/assets/flags/no.svg' },
  { iso2: 'OM', name: 'Oman', phonePrefix: '+968', flagPath: '/assets/flags/om.svg' },
  { iso2: 'PK', name: 'Pakistan', phonePrefix: '+92', flagPath: '/assets/flags/pk.svg' },
  { iso2: 'PW', name: 'Palau', phonePrefix: '+680', flagPath: '/assets/flags/pw.svg' },
  { iso2: 'PS', name: 'Palestine', phonePrefix: '+970', flagPath: '/assets/flags/ps.svg' },
  { iso2: 'PA', name: 'Panama', phonePrefix: '+507', flagPath: '/assets/flags/pa.svg' },
  { iso2: 'PG', name: 'Papua New Guinea', phonePrefix: '+675', flagPath: '/assets/flags/pg.svg' },
  { iso2: 'PY', name: 'Paraguay', phonePrefix: '+595', flagPath: '/assets/flags/py.svg' },
  { iso2: 'PE', name: 'Peru', phonePrefix: '+51', flagPath: '/assets/flags/pe.svg' },
  { iso2: 'PH', name: 'Philippines', phonePrefix: '+63', flagPath: '/assets/flags/ph.svg' },
  { iso2: 'PL', name: 'Poland', phonePrefix: '+48', flagPath: '/assets/flags/pl.svg' },
  { iso2: 'PT', name: 'Portugal', phonePrefix: '+351', flagPath: '/assets/flags/pt.svg' },
  { iso2: 'QA', name: 'Qatar', phonePrefix: '+974', flagPath: '/assets/flags/qa.svg' },
  { iso2: 'RO', name: 'Romania', phonePrefix: '+40', flagPath: '/assets/flags/ro.svg' },
  { iso2: 'RU', name: 'Russia', phonePrefix: '+7', flagPath: '/assets/flags/ru.svg' },
  { iso2: 'RW', name: 'Rwanda', phonePrefix: '+250', flagPath: '/assets/flags/rw.svg' },
  { iso2: 'WS', name: 'Samoa', phonePrefix: '+685', flagPath: '/assets/flags/ws.svg' },
  { iso2: 'KN', name: 'Saint Kitts and Nevis', phonePrefix: '+1-869', flagPath: '/assets/flags/kn.svg' },
  { iso2: 'LC', name: 'Saint Lucia', phonePrefix: '+1-758', flagPath: '/assets/flags/lc.svg' },
  { iso2: 'VC', name: 'Saint Vincent and the Grenadines', phonePrefix: '+1-784', flagPath: '/assets/flags/vc.svg' },
  { iso2: 'SM', name: 'San Marino', phonePrefix: '+378', flagPath: '/assets/flags/sm.svg' },
  { iso2: 'ST', name: 'Sao Tome and Principe', phonePrefix: '+239', flagPath: '/assets/flags/st.svg' },
  { iso2: 'SA', name: 'Saudi Arabia', phonePrefix: '+966', flagPath: '/assets/flags/sa.svg' },
  { iso2: 'SN', name: 'Senegal', phonePrefix: '+221', flagPath: '/assets/flags/sn.svg' },
  { iso2: 'RS', name: 'Serbia', phonePrefix: '+381', flagPath: '/assets/flags/rs.svg' },
  { iso2: 'SC', name: 'Seychelles', phonePrefix: '+248', flagPath: '/assets/flags/sc.svg' },
  { iso2: 'SL', name: 'Sierra Leone', phonePrefix: '+232', flagPath: '/assets/flags/sl.svg' },
  { iso2: 'SG', name: 'Singapore', phonePrefix: '+65', flagPath: '/assets/flags/sg.svg' },
  { iso2: 'SK', name: 'Slovakia', phonePrefix: '+421', flagPath: '/assets/flags/sk.svg' },
  { iso2: 'SI', name: 'Slovenia', phonePrefix: '+386', flagPath: '/assets/flags/si.svg' },
  { iso2: 'SB', name: 'Solomon Islands', phonePrefix: '+677', flagPath: '/assets/flags/sb.svg' },
  { iso2: 'SO', name: 'Somalia', phonePrefix: '+252', flagPath: '/assets/flags/so.svg' },
  { iso2: 'ZA', name: 'South Africa', phonePrefix: '+27', flagPath: '/assets/flags/za.svg' },
  { iso2: 'KR', name: 'South Korea', phonePrefix: '+82', flagPath: '/assets/flags/kr.svg' },
  { iso2: 'SS', name: 'South Sudan', phonePrefix: '+211', flagPath: '/assets/flags/ss.svg' },
  { iso2: 'ES', name: 'Spain', phonePrefix: '+34', flagPath: '/assets/flags/es.svg' },
  { iso2: 'LK', name: 'Sri Lanka', phonePrefix: '+94', flagPath: '/assets/flags/lk.svg' },
  { iso2: 'SD', name: 'Sudan', phonePrefix: '+249', flagPath: '/assets/flags/sd.svg' },
  { iso2: 'SR', name: 'Suriname', phonePrefix: '+597', flagPath: '/assets/flags/sr.svg' },
  { iso2: 'SZ', name: 'Swaziland', phonePrefix: '+268', flagPath: '/assets/flags/sz.svg' },
  { iso2: 'SE', name: 'Sweden', phonePrefix: '+46', flagPath: '/assets/flags/se.svg' },
  { iso2: 'CH', name: 'Switzerland', phonePrefix: '+41', flagPath: '/assets/flags/ch.svg' },
  { iso2: 'SY', name: 'Syria', phonePrefix: '+963', flagPath: '/assets/flags/sy.svg' },
  { iso2: 'TW', name: 'Taiwan', phonePrefix: '+886', flagPath: '/assets/flags/tw.svg' },
  { iso2: 'TJ', name: 'Tajikistan', phonePrefix: '+992', flagPath: '/assets/flags/tj.svg' },
  { iso2: 'TZ', name: 'Tanzania', phonePrefix: '+255', flagPath: '/assets/flags/tz.svg' },
  { iso2: 'TH', name: 'Thailand', phonePrefix: '+66', flagPath: '/assets/flags/th.svg' },
  { iso2: 'TL', name: 'Timor-Leste', phonePrefix: '+670', flagPath: '/assets/flags/tl.svg' },
  { iso2: 'TG', name: 'Togo', phonePrefix: '+228', flagPath: '/assets/flags/tg.svg' },
  { iso2: 'TO', name: 'Tonga', phonePrefix: '+676', flagPath: '/assets/flags/to.svg' },
  { iso2: 'TT', name: 'Trinidad and Tobago', phonePrefix: '+1-868', flagPath: '/assets/flags/tt.svg' },
  { iso2: 'TN', name: 'Tunisia', phonePrefix: '+216', flagPath: '/assets/flags/tn.svg' },
  { iso2: 'TR', name: 'Turkey', phonePrefix: '+90', flagPath: '/assets/flags/tr.svg' },
  { iso2: 'TM', name: 'Turkmenistan', phonePrefix: '+993', flagPath: '/assets/flags/tm.svg' },
  { iso2: 'TV', name: 'Tuvalu', phonePrefix: '+688', flagPath: '/assets/flags/tv.svg' },
  { iso2: 'UG', name: 'Uganda', phonePrefix: '+256', flagPath: '/assets/flags/ug.svg' },
  { iso2: 'UA', name: 'Ukraine', phonePrefix: '+380', flagPath: '/assets/flags/ua.svg' },
  { iso2: 'AE', name: 'United Arab Emirates', phonePrefix: '+971', flagPath: '/assets/flags/ae.svg' },
  { iso2: 'GB', name: 'United Kingdom', phonePrefix: '+44', flagPath: '/assets/flags/gb.svg' },
  { iso2: 'US', name: 'United States', phonePrefix: '+1', flagPath: '/assets/flags/us.svg' },
  { iso2: 'UY', name: 'Uruguay', phonePrefix: '+598', flagPath: '/assets/flags/uy.svg' },
  { iso2: 'UZ', name: 'Uzbekistan', phonePrefix: '+998', flagPath: '/assets/flags/uz.svg' },
  { iso2: 'VU', name: 'Vanuatu', phonePrefix: '+678', flagPath: '/assets/flags/vu.svg' },
  { iso2: 'VA', name: 'Vatican City', phonePrefix: '+39', flagPath: '/assets/flags/va.svg' },
  { iso2: 'VE', name: 'Venezuela', phonePrefix: '+58', flagPath: '/assets/flags/ve.svg' },
  { iso2: 'VN', name: 'Vietnam', phonePrefix: '+84', flagPath: '/assets/flags/vn.svg' },
  { iso2: 'YE', name: 'Yemen', phonePrefix: '+967', flagPath: '/assets/flags/ye.svg' },
  { iso2: 'ZM', name: 'Zambia', phonePrefix: '+260', flagPath: '/assets/flags/zm.svg' },
  { iso2: 'ZW', name: 'Zimbabwe', phonePrefix: '+263', flagPath: '/assets/flags/zw.svg' },
];

/**
 * Get country by ISO2 code
 */
export const getCountryByIso2 = (iso2: string): Country | undefined => {
  return COUNTRIES.find((c) => c.iso2 === iso2);
};

/**
 * Get country by phone prefix
 */
export const getCountryByPhonePrefix = (prefix: string): Country | undefined => {
  return COUNTRIES.find((c) => c.phonePrefix === prefix);
};
